server:
  port: 30013
  shutdown: graceful

spring:
  profiles:
    active: local
  application:
    name: batch
  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
  h2:
    console:
      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console  # H2 Console? Path
# Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)
  datasource:
    driver-class-name: org.h2.Driver  # Database? H2? ?????.
    url: jdbc:h2:file:./db/H2/data;AUTO_SERVER=true
    username: sa  # H2 ?? ? ??? username ?? (??? ??? ??)
    password: # H2 ?? ? ??? password ?? (??? ??? ??)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  batch:
    jdbc:
      initialize-schema: always