server:
  port: 30013
  shutdown: graceful

spring:
  profiles:
    active: local
  application:
    name: batch
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/H2/data;AUTO_SERVER=true
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  batch:
    jdbc:
      initialize-schema: always
  main:
    allow-bean-definition-overriding: true